### ISSUE TITLE
New Batch Abilities

### ISSUE THREAD

**Issue by fellars** [Airtable/airtable.js#112]
I see latest release has the batch functions available. Are they still not ready for production? or does this release mean they can be used in production?

Also, will they only work on accounts that have that beta turned on? or has it been rolled out to all accounts?

And documentation here says typecast works. My understanding was that typecast didn't yet work for batch. Has that been added?

Finally, is batch limit still 100 or has that been increased?  If still 100, will it be increased when ready for production? (please :) )

Thanks for getting this out there. Excited to start using!

**Comment by EvanHahn** [comment]
Batch operations are currently in beta, both for Airtable.js and the "main" Airtable API. In other words, they're **not ready for production yet**.

If you want to be added to the batch API beta, please [fill out this short form](https://airtable.com/shr2Hk8bNAA6wp1zM) and we'll enable you.

`typecast` should work with batch operations during the beta.

The limit is 10 records per request. We may increase this limit in the future. It's much easier for us to increase this in the future than decrease it, so we picked something conservative. Still, it's 10 times better than what we had before, so hopefully it's a welcome improvement!

I should reiterate that batch API operations are in beta and _are not ready for production use_. Still, we'd love feedback! Let us know if you run into any issues or if anything else needs improvement.

Going to close this issue because I believe I've answered all of your questions, but feel free to tell me that's wrong and I can reopen.

**Comment by fellars** [comment]
Thanks Evan, I meant 10, not 100 :).  I have access to it on my account. But most of my work is done on behalf of clients, and I haven't requested it for their accounts yet.

Understood on it being beta. will just use for testing. 

 Good to know on the typecast. I was told otherwise so nice work there!

This will be a great addition to api.  I agree it will be easier to expand than contract.  Appreciate your efforts to get it out there.  Will let you know if I run into any issues with it.

Dan
