### ISSUE TITLE
Use with Angular JS

### ISSUE THREAD

**Issue by ismaelrumzan** [Airtable/airtable.js#114]
Hi
Could you give an example on how to use it with promise in Angular JS.
This is my example code:
            baseAirport('Airport Shuttle Requests').select({
                maxRecords: 10,
                view: 'All Departures and Arrivals',
                filterByFormula: "Email='" + $scope.form_email + "'"
            }).eachPage(function page(records, fetchNextPage) {
                records.forEach(function(record) {
                    console.log('Retrieved ', record.get('Name'));
                    $scope.result.append(record.get('Name'));
                });
                fetchNextPage();
            }, function done(error) {
                console.log(error);
            });
The data comes through but I don't how to connect it with a promise in angularJS so that the $scope.result gets refreshed in the DOM automatically

**Comment by EvanHahn** [comment]
I don't think any of the maintainers of this library are Angular experts, unfortunately. You might have better luck [posting on our Community Forum](https://community.airtable.com/c/api) or on [StackOverflow with the `airtable` tag](https://stackoverflow.com/questions/tagged/airtable).

However, using Airtable.js in the browser is strongly discouraged, since that will expose your API key to everyone who has access to that web page. You might wish to do this server-side.

This looks like a question and not a problem with Airtable.js, so I'm going to close this issue. If that's wrong and there _is_ a problem with Airtable.js, let me know and we'll reopen it.

**Comment by ismaelrumzan** [comment]
Thanks for that. I followed your advice and worked with a back-end developer to implement this in nodejs and express server

**Comment by EvanHahn** [comment]
Great! Let us know if we can help further.
