### ISSUE TITLE
typecast:true does not allow update by actual id

### ISSUE THREAD

**Issue by lookfirst** [Airtable/airtable.js#130]
Let's say I have a primary field record value of: 'abc'

`table.update('abc', data, {typecast: true})`

Does not work, results in a 404 error message.

I am trying to avoid having to do a select to get the internal id first in order to do an update. It would save me an API hit to do that.

I would have hoped this would work because if I update a linked field record based on the primary field value, it magically works when `{typecase: true}`, which is awesome.

**Comment by EvanHahn** [comment]
That's an interesting suggestion! This isn't something the API supports at the moment, so you'll need to do a lookup first, but this idea has been noted.

I'd also advise light caution when using the `typecast` parameter. For simple strings lookups, there's not much to worry about—we grab the first thing we match, if it exists, creating a new one otherwise—but issues can come up in the world of edge cases. For example, how would you match a primary cell value that was a date? Would you _only_ match on ISO string? What if you passed a date with no time but the field had times? And that's just for dates.

But that's an aside—we'll note this suggestion and consider it as we work on the API.

If you feel that your question has been answered, feel free to close this issue. If not, we'll leave it open until we address this fully.

**Comment by lookfirst** [comment]
All of my primary id's are simple strings.

I don't understand the comment of 'creating a new one otherwise'. Does that mean that if I add an ID that does not already exist in a linked field, that it will create a new row in that linked table? That seems really dangerous. I would expect that the row would have to exist already at least.

**Comment by EvanHahn** [comment]
Imagine you have two tables in your base: _People_ and _Colors_. Each person in the _People_ table has favorite colors, which is a linked record to the _Colors_ table.

If you make a request like this:

```js
base('People').create({
  Name: 'Jon',
  'Favorite colors': ['recxxxxxxxxxxxxxx']
})
```

If `recxxxxxxxxxxxxxx` exists in the _Colors_ table, the link will be created. Otherwise, it will fail. But if you send a request like this:

```js
base('People').create({
  Name: 'Jon',
  'Favorite colors': ['Orange']
}, {typecast: true})
```

If there's a record whose primary cell value is "Orange" in the _Colors_, we'll link to that record. If no record like that exists, a new record will be created with the primary cell value, "Orange", and your favorite colors will point there.

This linked records + `typecast` behavior is the same for updates and creates.

Because all of your primary cell values are simple strings, you should be fine to use `typecast` for this purpose. But your original question isn't currently possible—you'll still need to do a lookup before you do the update.

**Comment by lookfirst** [comment]
Thanks for the excellent response. You should write that into the API documentation. =)

Let's say I have a 'People' table. Then I have a 'Trees' table with a field 'plantedBy:', which is a linked field to the People table.

If you end up adding a row to the People table every time plant a tree with a person who isn't in there, that would be bad for me. I'd prefer it just to error out.

But whatever... that's fine... I'm migrating off Airtable. I kind of suspected I would have to do it sooner or later but after doing a bit more testing, I've found cases where the lack of transactions has left me with weird data in a very hard to diagnose way. It is clear the api is focused on super basic uses cases. That's fine... not a slight on you guys at all. I was trying to avoid having to build a UI myself, but shrug, just more code. Thanks again.
