### ISSUE TITLE
Replace request lib

### ISSUE THREAD

**Issue by cktang88** [Airtable/airtable.js#153]
Request is very bloated - https://bundlephobia.com/result?p=request@2.88.0

Can possibly replace with https://bundlephobia.com/result?p=node-fetch@2.6.0 or https://bundlephobia.com/result?p=axios@0.19.0 or something similar?

**Comment by EvanHahn** [comment]
We've had some other issues about bundle size (#75 and #108 come to mind).

I'm not opposed to this, but I think the urgency is low.

We replace `request` with `xhr` in the browser, which is [significantly smaller](https://bundlephobia.com/result?p=xhr@2.3.3). On top of that, we discourage Airtable.js's use in the browser because it will expose your API key to everyone who has access to that web page.

Are you running Airtable.js in an environment where the bundle size is significant? I'd love to know more about your use case.

**Comment by fsubal** [comment]
The `request` module is deprecated on Feb 11th 2020 ( https://github.com/request/request ).

I wonder `xhr` for browser should also be migrated ( and integrated to one library ? ), but for node environment, I think it came to be urgent now.

**Comment by fsubal** [comment]
Related: #167

**Comment by minicat** [comment]
The `request` library has been replaced with `node-fetch`: https://github.com/Airtable/airtable.js/pull/191
