### ISSUE TITLE
conditional load node-fetch

### ISSUE THREAD

**Issue by jimmywarting** [Airtable/airtable.js#288]
https://github.com/Airtable/airtable.js/blob/9d40666979af77de9546d43177cab086a03028bf/src/fetch.ts#L1-L5

May i suggest the following instead: 

```js
export default = globalThis.fetch || async function fetch(...args) {
  const {default: fetch} = new Function('return import("node-fetch")')()
  return fetch(...args))
}
```

**Comment by albreyb** [comment]
In order to mitigate bugs, have a strong preference to knowing the version of nodefetch that is running inside of Airtable js. At this time, we don't want to rely on an existing global fetch installation. For that reason, we are closing this issue.

**Comment by marcvangend** [comment]
While I understand your reasons to close this issue, I respectfully ask you to reconsider.

This week, NextJS 13 was released. Its [documentation](https://beta.nextjs.org/docs/data-fetching/fetching) says:
> React and Next.js 13 introduced a new way to fetch and manage data in your application. The new data fetching system works in the app directory and is built on top of the [fetch() Web API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API).
>
> `fetch()` is a Web API used to fetch remote resources and returns a promise. React extends `fetch` to provide [automatic request deduping](https://beta.nextjs.org/docs/data-fetching/fundamentals#automatic-fetch-request-deduping), and Next.js extends the `fetch` options object to allow each request to set its own [caching and revalidating](https://beta.nextjs.org/docs/data-fetching/caching).

If I'm not mistaken, the fact that airtable always uses `node-fetch` even if a global `fetch` is available, means that it is preventing users from taking advantage of features built into React and NextJS.

Instead of automatically selecting the global fetch, another option would be to allow injecting a fetch method with `Airtable.configure()`. This way you would keep the predictability of a known node-fetch version out-of-the-box, while allowing developers to opt-out.

**Comment by lsagetlethias** [comment]
I had the same problem with next's cache opti for their custom fetch function. I tried to resolve the issue with the PR #399
