### ISSUE TITLE
How do I use this library and keep my apiKey secret?

### ISSUE THREAD

**Issue by cinjon** [Airtable/airtable.js#308]
I am using React where the env vars read as, for example `process.env.REACT_APP_AIRTABLE_API_KEY`, are not secret. They are exposed in the build. This library, while wonderful, doesn't seem to have a way to let me interact with it on the backend or otherwise in a fashion that preserves the secrecy of the apiKey.

How are people dealing with this? What's the recommended approach?

**Comment by netgfx** [comment]
I assume you can use nodejs to make all the interactions with the DB on the backend, since they offer normal REST API and they have a javascript SDK

**Comment by davisburnside** [comment]
You should be accessing your API key in back-end logic running on a server or a serverless cloud function. I use Firebase to handle that.

**Comment by DannyMatteson-at** [comment]
Agree with using airtable.js in nodejs to handle your API keys securely there instead of client-side. Closing this Issue now, thanks for reaching out @cinjon ! If you have general inquiries about using the developer features like the API and airtable.js, we encourage you to use our official support channels at https://support.airtable.com/docs/search?query=api+errors&searchType=articles (click the black chat bubble in the bottom right corner). Thanks!
