### ISSUE TITLE
maxRecords description in API docs is misleading

### ISSUE THREAD

**Issue by avoidwork** [Airtable/airtable.js#66]
Hi,

I recently ran into an unexpected problem using the node.js lib, and sample code generated on the api docs for a table.

The following is from your documentation:

```
maxRecords (number)
optional

The maximum total number of records that will be returned.
```

However, this is misleading. It is not the total number of records returned, but the total records used for server-side pagination via cursor, e.g. if you spec 100 you can only ever get 100. To paginate properly you have to not specify this value.

This is not clearly explained anywhere. As someone trying to paginate a data set, it's implied to be the page size because "returned" is in the description.

**Comment by EvanHahn** [comment]
Thanks for reporting this—we'll look into clarifying the documentation.

There are two options that directly affect the number of records returned: `pageSize` and `maxRecords`. `pageSize` affects the number of records per page, but if you load all of the pages, it doesn't matter what you set this to.

If you have a base that has 234 records, `"pageSize": 3` will require 78 requests to download the whole table; `"pageSize": 100` will require 3 requests.

If you have a base that has 234 records, `"maxRecords": 5` will only return the first five records; `"maxRecords": 123` will return two pages, one with the first 100 records, one with 23 records; `"maxRecords": 999` doesn't do anything because the base has fewer than 999 records.

Does that make sense? Again, we'll look into improving our docs around this.

**Comment by avoidwork** [comment]
Hi,

Yes, I understand how it's working. The problem as I see it is that the 'List Records' sample on your at `/api/docs#nodejs/table:articles:list` has a `maxRecords: 3` specified, and the content below has this form...

```
maxRecords (number)
optional

The maximum total number of records that will be returned.

pageSize (number)
optional
The number of records returned in each request. Must be less than or equal to 100. Default is 100.
```

_If_ the sample instead used `pageSize` & the description of `maxRecords` was changed to clarify what "returns" means there'd be less frustration. My first intuition was to change `maxRecords` to match `pageSize`.

**Comment by EvanHahn** [comment]
Agreed.

We'll update our docs so that you're the last to have this confusion!

**Comment by EvanHahn** [comment]
We've updated our docs to better describe `maxRecords` and `pageSize`. Closing this issue, but let us know if you have any other confusion!
